### ISSUE TITLE
Write documentation for usage

### ISSUE THREAD

**Issue by jackrod** [bluemagicsource/magic-config#5]
Use wiki on bluemagicsource.org

**Comment by jackrod** [comment]
Look into transformation of java based comments into html

**Comment by PeterPlatt** [comment]
Probably should consider doxygen which can transform source comments to documentation. I'll look into this soon too. Below is a link to getting started documentaion

http://www.stack.nl/~dimitri/doxygen/starting.html

**Comment by PeterPlatt** [comment]
Actually may not need to be that complicated. Seems the java docs converts to HTML very easily. I'll examine that approach instead

**Comment by PeterPlatt** [comment]
we can use javadoc to generate our documentation. The only thing that concerns me is that our public methods aren't all well documented. I'll begin the process of attempting to transform our comments soon.

**Comment by PeterPlatt** [comment]
Used javadoc to generate basic HTML pages. Email sent to Jrod we may need to do some more CSS work to clean up the look and feel, but I feel the focus should be on good documentation first.
